import { Product, StoreSettings } from './types';

export const INITIAL_JEWELRY_BOX_PRODUCT: Product = {
  id: 'prod-jewelry-box-01',
  slug: 'jewelry-box',
  name: 'Portable Mini Travel Jewelry Box',
  nameBn: 'প্রিমিয়াম মিনি পোর্টেবল ট্রাভেল জুয়েলারি বক্স',
  taglineBn: 'শখের গহনা ও প্রসাধন সুরক্ষিত রাখুন নিখুঁত পরিপাটীভাবে — যেকোনো ভ্রমণের সেরা সঙ্গী!',
  descriptionBn: 'আমাদের এই কিউট এবং কম্প্যাক্ট পোর্টেবল জুয়েলারি বক্সটি আপনার প্রিয় আংটি, কানের দুল, নেকলেস, চেইন এবং ঘড়ি গুছিয়ে রাখার জন্য ডিজাইন করা হয়েছে। উন্নতমানের ওয়াটারপ্রুফ PU লেদার এক্সটেরিয়র এবং ভেতরের সফট ভেলভেট লাইনিং আপনার মূল্যবান গহনাকে স্ক্র্যাচ ও ধুলাবালি থেকে সুরক্ষিত রাখে।',
  category: 'Travel Organizer & Gifting',
  rating: 4.9,
  reviewCount: 128,
  basePrice: 499,
  originalPrice: 750,
  images: [
    '/images/products/hello-kitty-pair.png',
    '/images/products/hello-kitty-open.png',
    '/images/products/pink-box-interior.png',
    '/images/products/mandala-boxes.png',
  ],
  variants: [
    {
      id: 'var-pink-kitty',
      name: 'Hello Kitty Soft Pink',
      nameBn: 'হ্যালো কিটি বেবি পিঙ্ক (Baby Pink)',
      color: 'Baby Pink',
      colorHex: '#f9a8d4',
      image: '/images/products/hello-kitty-pair.png',
      inStock: true,
      stockCount: 45,
    },
    {
      id: 'var-white-kitty',
      name: 'Hello Kitty Pearl White',
      nameBn: 'হ্যালো কিটি পার্ল হোয়াইট (Pearl White)',
      color: 'Pearl White',
      colorHex: '#f8fafc',
      image: '/images/products/hello-kitty-open.png',
      inStock: true,
      stockCount: 38,
    },
    {
      id: 'var-mandala-cork',
      name: 'Vintage Mandala & Butterfly',
      nameBn: 'ভিন্টেজ কর্ক মান্দালা (Vintage Mandala)',
      color: 'Vintage Multi',
      colorHex: '#d97706',
      image: '/images/products/mandala-boxes.png',
      inStock: true,
      stockCount: 25,
    },
  ],
  combos: [
    {
      id: 'combo-single',
      title: 'Single Box (1 Piece)',
      titleBn: '১টি জুয়েলারি বক্স (সিঙ্গেল প্যাক)',
      subtitleBn: 'নিজের জন্য বা ছোট উপহারের জন্য',
      quantity: 1,
      price: 499,
      originalPrice: 750,
      savingsBn: '২৫১ টাকা সাশ্রয়',
    },
    {
      id: 'combo-duo',
      title: 'Bestie Combo (2 Pieces)',
      titleBn: '২টি বক্স বেস্টি কম্বো (Best Deal)',
      subtitleBn: '১টি আপনার জন্য + ১টি প্রিয় বান্ধবীর জন্য',
      quantity: 2,
      price: 899,
      originalPrice: 1500,
      badge: '🔥 সর্বাধিক বিক্রিত অফার (Save ৳১০০ Extra)',
      isPopular: true,
      savingsBn: '৬০১ টাকা সাশ্রয় (সেরা ডিল)',
    },
    {
      id: 'combo-trio',
      title: 'Mega Gift Pack (3 Pieces)',
      titleBn: '৩টি বক্স মেগা ফ্যামিলি প্যাক',
      subtitleBn: 'গিফটিং ও ট্রাভেলের সেরা প্যাকেজ',
      quantity: 3,
      price: 1249,
      originalPrice: 2250,
      badge: '🎁 মেগা সেভিংস অফার',
      savingsBn: '১,০০১ টাকা মেগা সেভিংস',
    },
  ],
  featuresBn: [
    {
      icon: 'Sparkles',
      title: 'কম্প্যাক্ট ও সহজে বহনযোগ্য',
      description: 'হাতের তালুর সমান সাইজ (১০ x ১০ x ৫ সেমি), ভ্যানিটি ব্যাগ বা ট্রাভেল ব্যাগে সহজেই জায়গা হয়ে যায়।',
    },
    {
      icon: 'ShieldCheck',
      title: 'স্ক্র্যাচপ্রুফ সফট ভেলভেট লাইনিং',
      description: 'ভেতরের নরম ভেলভেট ক্লথ আপনার সোনা, রূপা ও ডায়মন্ডের গহনাকে যেকোনো দাগ বা ঘষা থেকে সুরক্ষিত রাখে।',
    },
    {
      icon: 'Layers',
      title: 'মাল্টি-কম্পার্টমেন্ট পার্টিশন',
      description: 'আংটির জন্য ৬টি স্লট, ৩টি নেকলেস হ্যাঙ্গার ও পকেট, এবং কানের দুল/ঘড়ির জন্য রিমুভেবল চেম্বার।',
    },
    {
      icon: 'Gift',
      title: 'অপূর্ব গিফট প্যাকেজিং',
      description: 'প্রিয় মানুষের জন্মদিন, বিবাহবার্ষিকী বা বিশেষ যেকোনো দিনে উপহার দেওয়ার মতো আকর্ষণীয় লুক।',
    },
  ],
  specificationsBn: [
    { key: 'মেটেরিয়াল', value: 'প্রিমিয়াম ওয়াটারপ্রুফ PU লেদার + সফট ভেলভেট ইনার' },
    { key: 'সাইজ', value: '১০ সেমি x ১০ সেমি x ৫ সেমি' },
    { key: 'ওজন', value: 'মাত্র ১৫০ গ্রাম (সুপার লাইটওয়েট)' },
    { key: 'চেম্বার', value: '৬টি রিং স্লট, ৩টি নেকলেস হুক, ৪টি ফ্লেক্সিবল কম্পার্টমেন্ট' },
    { key: 'লক সিস্টেম', value: 'স্মুথ মেটাল জিপার সিকিউর লক' },
  ],
  isActive: true,
};

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'Subinyas',
  storeNameBn: 'সুবিন্যাস',
  phone: '01617492486',
  whatsappNumber: '8801617492486',
  metaPixelId: '1234567890123456',
  deliveryInsideDhaka: 70,
  deliveryOutsideDhaka: 130,
  announcementTextBn: '🚚 সারাদেশে দ্রুত ক্যাশ অন ডেলিভারি সুবিধা!',
  isPixelActive: true,
};
